name: WordPress CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging
        env:
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          # Build and push Docker image
          docker build -t my-wordpress .
          docker push my-wordpress:latest
          
          # Deploy to staging server
          ssh user@staging-host 'docker pull my-wordpress:latest && docker stop my-wordpress && docker rm my-wordpress && docker run -d --name my-wordpress -p 8000:80 my-wordpress:latest'
